name: Build Debian Images

on:
  push:
    branches:
      - 1.16-debian
  workflow_dispatch: # 允许手动触发

env:
  BUILD_VERSION: v1.16.0

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/kasm-debian-bookworm-desktop.dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-amd64
            registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-amd64
          build-args: |
            BASE=ghcr.io/${{ github.repository_owner }}/kasm-core:${{ env.BUILD_VERSION }}-debian12-amd64
            TARGETOS=linux
            TARGETARCH=amd64
          provenance: false
          sbom: false

      - name: Build and push images for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/kasm-debian-bookworm-desktop.dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-arm64
            registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-arm64
          build-args: |
            BASE=ghcr.io/${{ github.repository_owner }}/kasm-core:${{ env.BUILD_VERSION }}-debian12-arm64
            TARGETOS=linux
            TARGETARCH=arm64
          provenance: false
          sbom: false

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12 \
            ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-amd64 \
            ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-arm64
          docker manifest push ghcr.io/${{ github.repository }}/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12

          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12 \
            registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12-arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/bdwind-vnc:${{ env.BUILD_VERSION }}-debian12
